# Generated by Django 3.2.5 on 2021-08-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_auto_20210822_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='event_day',
        ),
    ]
