# Generated by Django 3.2.5 on 2021-08-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='national_id',
            new_name='course_code',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='county',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='date_of_enrollement',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='email_adress',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='image',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='laptop_number',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='nationality',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_schedule',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_trainer',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='syllabus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
