# Generated by Django 3.2.5 on 2021-10-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_trainer',
            field=models.CharField(max_length=78, null=True),
        ),
    ]
