# Generated by Django 3.2.5 on 2021-09-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210816_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
