# Generated by Django 3.2.5 on 2021-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='national_id',
            new_name='event_id',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='last_name',
        ),
        migrations.AddField(
            model_name='calender',
            name='event_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='calender',
            name='event_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='calender',
            name='event_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calender',
            name='event_participants',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calender',
            name='event_planner',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calender',
            name='venue',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
