# Generated by Django 3.2.5 on 2021-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_auto_20210816_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='calender',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
